# -*- coding: utf-8 -*-
"""
Base de nomes e sobrenomes usada para gerar o dataset fictício de RH.

Origem: lista fornecida pelo usuário (598 nomes masculinos, 698 femininos,
683 sobrenomes — incluindo origem italiana, alemã e japonesa, refletindo a
imigração real do sul/sudeste do Brasil). Ampliada abaixo com mais algumas
dezenas de nomes/sobrenomes comuns para aumentar ainda mais a diversidade
regional (nomes indígenas, nordestinos e contemporâneos), conforme pedido
no Artigo 4 (propósito pedagógico > estética) — mais variedade de nomes
gera menos colisões e listas de PROCV mais realistas.
"""

NOMES_MASCULINOS = [  # 598 únicos — fornecidos pelo usuário
    "João", "Pedro", "Lucas", "Gabriel", "Mateus", "Rafael", "Daniel", "André",
    "Felipe", "Rodrigo", "Bruno", "Marcelo", "Eduardo", "Gustavo", "Henrique", "Leonardo",
    "Alexandre", "Carlos", "Paulo", "Roberto", "Diego", "Fernando", "Leandro", "Márcio",
    "Renato", "Sérgio", "Thiago", "Victor", "Wagner", "Anderson", "Arthur", "Heitor",
    "Bento", "Cauã", "Ryan", "Nathan", "Yan", "Ian", "Alan", "Renan",
    "Brenno", "Benício", "Gael", "Matteo", "Erick", "Rayan", "Nícolas", "Luca",
    "Théo", "Noah", "Lorenzo", "Luiz", "Kauan", "Kevin", "Luan", "Murilo",
    "Nelson", "Otávio", "Patrick", "Ricardo", "Samuel", "Tiago", "Vinicius", "Wellington",
    "Enzo", "Iago", "Antônio", "Caio", "Cláudio", "Davi", "Elias", "Fábio",
    "Guilherme", "Igor", "Julio", "Adriano", "Bernardo", "Cícero", "Dário", "Francisco",
    "Giovani", "Humberto", "Ulisses", "Xavier", "Yago", "Breno", "Caetano", "Cassiano",
    "Celso", "Cristiano", "Dalton", "Damião", "Danilo", "Denis", "Domingos", "Donizete",
    "Dorival", "Duarte", "Edison", "Edson", "Edvaldo", "Emerson", "Erasmo", "Eugênio",
    "Eurico", "Evaldo", "Evandro", "Everton", "Ezequiel", "Fabrício", "Fausto", "Feliciano",
    "Félix", "Filipe", "Flávio", "Franklin", "Frederico", "Geraldo", "Gerson", "Gil",
    "Gilberto", "Gilmar", "Gilson", "Gláuber", "Glauco", "Helton", "Hermes", "Hélio",
    "Higor", "Hilário", "Hilton", "Honório", "Horácio", "Inácio", "Irineu", "Isac",
    "Isaías", "Isidoro", "Ismael", "Ítalo", "Ivan", "Ivanildo", "Jacinto", "Jaime",
    "Jailson", "Jair", "Jander", "Jardel", "Jefferson", "Jerônimo", "Joel", "Jonatan",
    "Jonas", "Jordan", "Jorge", "José", "Josias", "Juarez", "Jurandir", "Juvenal",
    "Kleber", "Laercio", "Lauro", "Lazaro", "Lênio", "Leonidas", "Leonel", "Levi",
    "Lindomar", "Lineu", "Lúcio", "Magno", "Maicon", "Marcos", "Mariano", "Mário",
    "Moisés", "Natan", "Natanael", "Nildo", "Nilo", "Nilson", "Noé", "Noel",
    "Orlando", "Osmar", "Oswaldo", "Otacílio", "Otto", "Ovídio", "Paulino", "Péricles",
    "Plínio", "Raimundo", "Ramon", "Raoni", "Renildo", "Rivaldo", "Robson", "Rodolfo",
    "Romário", "Ronaldo", "Roni", "Roque", "Rubem", "Rubens", "Rudimar", "Rui",
    "Salomão", "Saulo", "Sebastião", "Silvano", "Silvestre", "Silvio", "Solon", "Teobaldo",
    "Tibério", "Timóteo", "Tito", "Tobias", "Tomás", "Valdemir", "Valdir", "Valério",
    "Valentim", "Valmir", "Vanderlei", "Vasco", "Venâncio", "Vidal", "Vilmar", "Vilson",
    "Virgílio", "Vitório", "Waldemar", "Waldir", "Wanderlei", "Wesley", "Willian", "Wladimir",
    "Zeferino", "Zito", "Abner", "Abraão", "Acácio", "Adalberto", "Adão", "Adelino",
    "Ademir", "Adolfo", "Agostinho", "Aguinaldo", "Aírton", "Alceu", "Alcides", "Alcino",
    "Alcir", "Aldo", "Alessandro", "Alisson", "Almir", "Altair", "Altino", "Altemiro",
    "Amaro", "Amílton", "Anísio", "Anselmo", "Aparecido", "Ariel", "Arlindo", "Armando",
    "Arnaldo", "Artur", "Ary", "Augusto", "Aurelio", "Balbino", "Baldomiro", "Baltazar",
    "Basílio", "Benedito", "Adilson", "Admar", "Aldair", "Alencar", "Alexsandro", "Ambrozio",
    "Amintas", "Amós", "Anchieta", "Antero", "Apolo", "Aquiles", "Arcanjo", "Argemiro",
    "Aristeu", "Aristides", "Armindo", "Arnildo", "Arno", "Astolfo", "Átila", "Átilio",
    "Aureliano", "Aureo", "Auro", "Azor", "Bibiano", "Bladimir", "Bonifácio", "Boaventura",
    "Creomar", "Crispim", "Custódio", "Dagoberto", "Darlan", "Décio", "Deivid", "Delmar",
    "Deoclécio", "Deodato", "Dionísio", "Divaldo", "Diógenes", "Duílio", "Djalma", "Edgar",
    "Edmundo", "Edevaldo", "Edilson", "Edmar", "Egídio", "Elcio", "Elói", "Emídio",
    "Epitácio", "Érico", "Ermínio", "Eraldo", "Ervino", "Esmeraldo", "Estevão", "Euclydes",
    "Eulalio", "Eustáquio", "Ezio", "Florisvaldo", "Gumercindo", "Helvécio", "Idário", "Iêdo",
    "Ilton", "Ivaldo", "Ivanor", "Ivano", "Ivens", "Ivo", "Jânio", "Joseilton",
    "Josevaldo", "Josivaldo", "Josnei", "Juberto", "Juaci", "Kadmo", "Kaio", "Kalil",
    "Lenivaldo", "Libânio", "Lindolfo", "Linério", "Lívio", "Lucídio", "Malaquias", "Manoelito",
    "Marcelino", "Marivaldo", "Melchior", "Moab", "Naircio", "Nairo", "Naldo", "Neomício",
    "Nerian", "Nerison", "Nerivaldo", "Nemias", "Norberto", "Norton", "Odir", "Odirlei",
    "Olavo", "Oldair", "Onildo", "Onório", "Orestes", "Osvaldir", "Palmério", "Policarpo",
    "Pompeu", "Porfirio", "Quincas", "Quintino", "Rangel", "Renoir", "Reuben", "Rosenaldo",
    "Rosendo", "Rosalvo", "Sabino", "Sandrinho", "Selso", "Severino", "Sidnei", "Sidney",
    "Simião", "Sinézio", "Siranildo", "Vanderlino", "Varino", "Vladmir", "Volmar", "Walace",
    "Waldo", "Wander", "Warley", "Watila", "Weverson", "Wiliam", "Wolmir", "Ângelo",
    "Cesário", "Dante", "Dino", "Ettore", "Franco", "Gino", "Pietro", "Romano",
    "Sandro", "Vito", "Luigi", "Massimo", "Aníbal", "Nerino", "Tino", "Osvaldo",
    "Ernst", "Klaus", "Kurt", "Rudolf", "Werner", "Dieter", "Erich", "Fritz",
    "Hans", "Heinz", "Hermann", "Karl", "Ingo", "Rolf", "Alwin", "Uwe",
    "Lothar", "Udo", "Kenji", "Hiroshi", "Yoshio", "Takashi", "Kazuo", "Massao",
    "Akira", "Nobuo", "Toshio", "Seiji", "Koji", "Makoto", "Naoki", "Satoshi",
    "Tadashi", "Shoiti", "Álvaro", "César", "Célio", "Cristóvão", "Edilberto", "Ednaldo",
    "Edmilson", "Erivaldo", "Ernani", "Euclides", "Faustino", "Floriano", "Gelson", "Genar",
    "Glenison", "Haroldo", "Harley", "Heleno", "Helvio", "Herberto", "Hercílio", "Herenildo",
    "Ibraim", "Ilmo", "Inocêncio", "Iosvaldo", "Iremar", "Irineo", "Isnaldo", "Ivander",
    "Jaci", "Jaco", "Jaderson", "Jadir", "Jairo", "Jalmir", "Jamilton", "Jandir",
    "Janio", "Jarbas", "Jario", "Javier", "Jeanderson", "Jeovani", "Jeter", "Joaldo",
    "Joatan", "Joelson", "Joevaldo", "Joilson", "Joimar", "Joinville", "Jonailton", "Jonalvo",
    "Jonathan", "Jonilson", "Jonilton", "Josemar", "Jucelino", "Jucimar", "Junio", "Kléber",
    "Ladislau", "Laionê", "Lajar", "Lajônio", "Lamar", "Landrio", "Laudemir", "Laudivino",
    "Leocádio", "Leodegar", "Leodilson", "Leonildo", "Leudimar", "Lidemir", "Liduino", "Lino",
    "Lisandro", "Lorival", "Lourival", "Lucelino", "Luciano", "Luizinho", "Maciel", "Magnaldo",
    "Maguinaldo", "Mailo", "Mainar", "Mainardo", "Mairan", "Malico", "Maneco", "Manoaldo",
    "Marceliano", "Marciliano", "Marcílio", "Marcondes", "Marlon", "Marvaldo", "Marvino", "Mauro",
    "Maximo", "Moacir", "Moacyr", "Moises", "Moreira", "Mórion", "Nabor", "Nadim",
    "Naelson", "Nailton", "Nailzo", "Naimar", "Narciso", "Nardo",
]

NOMES_FEMININOS = [  # 698 únicos — fornecidos pelo usuário
    "Ana", "Maria", "Fernanda", "Juliana", "Patrícia", "Camila", "Aline", "Beatriz",
    "Carolina", "Daniela", "Elisa", "Gabriela", "Helena", "Isabela", "Jéssica", "Larissa",
    "Mariana", "Natália", "Olivia", "Paula", "Raquel", "Sabrina", "Tatiana", "Vanessa",
    "Yasmin", "Amanda", "Bruna", "Cristina", "Débora", "Eduarda", "Flávia", "Giovanna",
    "Heloísa", "Ingrid", "Joyce", "Karen", "Letícia", "Mônica", "Nathália", "Priscila",
    "Rafaela", "Sandra", "Tânia", "Valéria", "Viviane", "Alice", "Bárbara", "Cíntia",
    "Diana", "Estela", "Fabiana", "Graziela", "Kelly", "Luciana", "Míriam", "Núbia",
    "Úrsula", "Haline", "Iolanda", "Jaciara", "Oriana", "Abigail", "Adélia", "Adelina",
    "Adriana", "Agda", "Aldaci", "Aldina", "Aldivina", "Alessandra", "Alzira", "Amélia",
    "Amélita", "Amira", "Angélica", "Antonieta", "Aparecida", "Araci", "Arlete", "Aurenilde",
    "Aurenice", "Áurea", "Auristela", "Benedita", "Bernadete", "Berenice", "Bianca", "Carmem",
    "Carmelita", "Catarina", "Cecília", "Celeste", "Célia", "Clara", "Conceição", "Dalva",
    "Dirce", "Dolores", "Doralice", "Doris", "Dulce", "Edna", "Edite", "Efigênia",
    "Elaine", "Elenita", "Elenira", "Eleonice", "Eleonora", "Eloísa", "Elsa", "Elvira",
    "Elzira", "Emília", "Estér", "Eunice", "Eva", "Evangelina", "Fátima", "Francisca",
    "Geralda", "Georgina", "Giselda", "Gisele", "Giseli", "Gizelia", "Glaucia", "Gloria",
    "Gorette", "Graça", "Graziele", "Idalina", "Ieda", "Iracema", "Iraci", "Irene",
    "Iris", "Isabel", "Isadora", "Ivanilde", "Ivone", "Ivonete", "Jandira", "Janete",
    "Jani", "Jaqueline", "Josefa", "Joselita", "Josiane", "Judite", "Julieta", "Katia",
    "Katiane", "Leda", "Leonor", "Lídia", "Lindalva", "Lourdes", "Luzia", "Madalena",
    "Magda", "Maíra", "Malvina", "Margarida", "Marli", "Marlene", "Marta", "Mercedes",
    "Mirtes", "Nadir", "Nair", "Neuza", "Nilza", "Nina", "Norma", "Odete",
    "Oneide", "Orlanda", "Palmira", "Perpétua", "Piedade", "Quelita", "Regina", "Reni",
    "Rita", "Rosa", "Rosana", "Rosângela", "Rosária", "Rosilene", "Rosmari", "Rosmary",
    "Ruth", "Sebastiana", "Silvia", "Simone", "Sônia", "Sueli", "Suely", "Suzana",
    "Tereza", "Therezinha", "Valdirene", "Vanda", "Vera", "Vilma", "Wanda", "Zélia",
    "Zenaide", "Acácia", "Acília", "Adalcina", "Adalgisa", "Adalina", "Adalmira", "Adenir",
    "Adenilde", "Adenita", "Adilma", "Adilza", "Adineide", "Adiná", "Adjanira", "Adlene",
    "Adnéia", "Adora", "Adriele", "Adrieli", "Adrielma", "Aelma", "Afrânea", "Aglaé",
    "Agnes", "Agripina", "Aguinara", "Aigara", "Ailine", "Ainaline", "Airan", "Airla",
    "Aisa", "Alaide", "Alcilene", "Alcimar", "Alcinéa", "Alcione", "Alda", "Aldenice",
    "Aldenira", "Aldenir", "Aldilene", "Aldilza", "Aldinara", "Alena", "Alertina", "Aleuda",
    "Alexsandra", "Aleyda", "Alfonsina", "Alicia", "Alípia", "Almira", "Alva", "Alvanete",
    "Alvanira", "Alves", "Alzinete", "Amabele", "Amadja", "Amairla", "Amara", "Amaralys",
    "Amedeane", "Anabela", "Anadir", "Anair", "Anairdes", "Anaís", "Analice", "Analícia",
    "Ananélia", "Anaraí", "Anarete", "Anari", "Anatilde", "Ancilena", "Andersa", "Andiara",
    "Anélia", "Anerinha", "Anete", "Aneuza", "Angelines", "Aniete", "Anisia", "Anizete",
    "Anniele", "Anunciada", "Apoline", "Aracelis", "Aracelir", "Arcelina", "Arcelinda", "Arcelino",
    "Arcelira", "Ardósia", "Ariane", "Ariel", "Arleuda", "Arneide", "Arnélia", "Arselina",
    "Artemia", "Arthurlina", "Aruca", "Ascelina", "Asilene", "Assis", "Assucena", "Ataíde",
    "Atília", "Audenira", "Audiete", "Audineide", "Audinete", "Audira", "Audirone", "Audinara",
    "Audinéia", "Audinélia", "Audinelma", "Audineuda", "Audirene", "Audires", "Audireth", "Auditene",
    "Auditina", "Augoura", "Auliene", "Aumira", "Aurilene", "Aurinete", "Auriselha", "Balbina",
    "Cândida", "Carmelinda", "Cartimandi", "Castorina", "Catilene", "Celmira", "Cessira", "Cilene",
    "Cileide", "Cileudo", "Cílene", "Cilinha", "Cirlei", "Cirlene", "Cirleni", "Cirlette",
    "Giovana", "Gina", "Lucia", "Elena", "Lena", "Carla", "Luana", "Lia",
    "Stefania", "Laura", "Valeria", "Ilse", "Hildegard", "Frida", "Gertrude", "Hermine",
    "Brigitte", "Greta", "Hilda", "Liselotte", "Yumi", "Akemi", "Harumi", "Michiko",
    "Sumiko", "Teruko", "Yoshiko", "Hiroko", "Sachiko", "Naomi", "Keiko", "Fumiko",
    "Kimiko", "Midori", "Noriko", "Setsuko", "Allana", "Allyne", "Allysson", "Alyne",
    "Amábile", "Amabilis", "Amaline", "Amandi", "Amandine", "Amarine", "Amaris", "Amayra",
    "Amba", "Ambra", "Ambrisia", "Amelie", "Amide", "Amiele", "Amiga", "Amilena",
    "Amilde", "Amiles", "Amilinha", "Amine", "Amineh", "Amiranda", "Amire", "Amireh",
    "Amirele", "Amireth", "Amiriane", "Amiris", "Amisabel", "Amisabela", "Amisandra", "Amisel",
    "Amisele", "Biah", "Brenda", "Catarine", "Celina", "Clarice", "Claudia", "Clarina",
    "Claris", "Clarisa", "Clarissa", "Clariste", "Clarita", "Claro", "Claudiane", "Claudiele",
    "Claudieli", "Claudilene", "Claudilma", "Claudilna", "Cléo", "Cleusa", "Cleuza", "Consuelo",
    "Cora", "Cordelia", "Corina", "Dagmar", "Dami", "Damiane", "Damiela", "Damilene",
    "Damineide", "Damira", "Danielle", "Dara", "Darcilene", "Darlane", "Darleni", "Darlete",
    "Darlley", "Darlliane", "Denise", "Denisia", "Denizia", "Deusdete", "Dilma", "Dinamar",
    "Dinalva", "Dinara", "Dinária", "Dinarilza", "Dinéa", "Dinélia", "Dinelise", "Dinelma",
    "Dinelza", "Dinete", "Eliane", "Elizabete", "Elisangela", "Elinalva", "Elinete", "Elinice",
    "Elinilda", "Elinor", "Eliodora", "Elionara", "Elionarda", "Elionice", "Elionilde", "Elionira",
    "Elizete", "Eliziene", "Elizilda", "Elizinete", "Elma", "Elmir", "Elmira", "Eloisa",
    "Eloise", "Eloisy", "Eloiza", "Elona", "Elonice", "Elonilda", "Elonira", "Elorá",
    "Eloris", "Elorisa", "Elorise", "Elorisete", "Elsie", "Elsiete", "Ivana", "Ivelise",
    "Ivelma", "Ivete", "Ivy", "Izabel", "Izabela", "Jana", "Janaina", "Janara",
    "Janiele", "Janilda", "Janine", "Janinna", "Jaquele", "Jara", "Jarina", "Jasmim",
    "Jassirene", "Jeane", "Jeanete", "Jeanine", "Jeiara", "Jeicy", "Jeniffer", "Jennifer",
    "Jéssyca", "Jewel", "Joana", "Joanice", "Joele", "Joelma", "Joélia", "Joice",
    "Joiciele", "Joliana", "Joliane", "Joliele", "Jordana", "Jordania", "Jordánia", "Joselma",
    "Josilene", "Josilma", "Josimara", "Juliara", "Julie", "Juliene", "Julieth", "Juliette",
    "Junia", "Junior", "Kamila", "Kamille", "Karina", "Karine", "Karla", "Kassia",
    "Kathryn", "Kauana", "Kayla", "Kendall", "Kezia", "Keziah", "Keziane", "Kézzia",
    "Kira", "Lara", "Larice", "Lariene", "Laris", "Larisa", "Larise", "Larissara",
    "Leonarda", "Leonie", "Leonilda", "Leonildes", "Leonilza", "Leonora", "Lian", "Liana",
    "Liane", "Liani", "Liara", "Liarys", "Lidia", "Lilian", "Liliane", "Lilis",
    "Lorena", "Lorene", "Loreni", "Lorenita", "Lorenna", "Lorenni", "Lorenny", "Lorenza",
    "Luciane", "Lucilene", "Lucilma", "Lucinara", "Lucineia", "Lucinete", "Lucinilda", "Luisa",
    "Luiza", "Luna", "Luziane", "Mabel", "Mabele", "Mabeline", "Mabella", "Maiana",
    "Maiara", "Maíara", "Maíca", "Maiena", "Maila", "Mailane", "Maina", "Milena",
    "Mileny", "Mileza", "Miliane", "Miliara", "Milice", "Miliele", "Nádia", "Naiara",
    "Naila", "Nailha", "Naime", "Nairane", "Naires", "Pamela", "Paola", "Pedrinha",
    "Perla", "Pilar", "Poliana", "Poliane", "Poliani", "Sofia", "Sofie", "Sonja",
    "Soraia", "Soraiara", "Soraiane", "Suiane", "Suiara", "Tainara", "Tainã", "Taise",
    "Tainá", "Taira", "Tamara", "Tamires", "Tatiara", "Valentina", "Valesca", "Valeska",
    "Valéska", "Valessa", "Vaniela", "Vitória", "Vivian", "Waleska", "Wanderléia", "Welma",
    "Wilza", "Winnie",
]

SOBRENOMES = [  # 683 únicos — fornecidos pelo usuário (origem lusa, italiana, alemã e japonesa)
    "Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Alves", "Pereira",
    "Lima", "Gomes", "Costa", "Ribeiro", "Martins", "Carvalho", "Almeida", "Lopes",
    "Soares", "Fernandes", "Vieira", "Barbosa", "Rocha", "Dias", "Nascimento", "Andrade",
    "Moreira", "Nunes", "Marques", "Machado", "Mendes", "Freitas", "Cardoso", "Ramos",
    "Gonçalves", "Santana", "Cruz", "Monteiro", "Teixeira", "Cavalcanti", "Correia", "Pinto",
    "Azevedo", "Melo", "Cunha", "Campos", "Fonseca", "Araújo", "Nogueira", "Peixoto",
    "Borges", "Moraes", "Farias", "Leite", "Matos", "Bezerra", "Castilho", "Guimarães",
    "Miranda", "Duarte", "Rezende", "Diniz", "Pires", "Magalhães", "Vasconcelos", "Barros",
    "Queiroz", "Assis", "Medeiros", "Brito", "Tavares", "Sampaio", "Bastos", "Silveira",
    "Lacerda", "Braga", "Pacheco", "Maia", "Lobato", "Prado", "Amaral", "Batista",
    "Abreu", "Aguiar", "Alencar", "Anjos", "Assunção", "Ávila", "Azambuja", "Basílio",
    "Bessa", "Bittencourt", "Boaventura", "Bonfim", "Brandão", "Bueno", "Cabral", "Caldas",
    "Camargo", "Campelo", "Carneiro", "Castro", "Cavalcante", "Chaves", "Coelho", "Couto",
    "Dantas", "Drumond", "Elias", "Esteves", "Falcão", "Figueiredo", "Figueira", "Flores",
    "Fontes", "Franco", "Freire", "Galvão", "Gama", "Garcia", "Gatto", "Gouveia",
    "Guerra", "Guedes", "Guerreiro", "Gusmão", "Henrique", "Holanda", "Leal", "Lemos",
    "Lisboa", "Loureiro", "Luz", "Macedo", "Maciel", "Marcelino", "Marinho", "Meireles",
    "Menezes", "Mesquita", "Moura", "Muniz", "Murta", "Neto", "Nóbrega", "Nonato",
    "Novais", "Paiva", "Passos", "Paula", "Pessoa", "Pinheiro", "Portela", "Primo",
    "Quadros", "Queirós", "Quintela", "Rego", "Reis", "Sacramento", "Salles", "Sales",
    "Santoro", "Saraiva", "Sardinha", "Sarmento", "Seabra", "Sena", "Serra", "Siqueira",
    "Sousa", "Taveira", "Travassos", "Trindade", "Vale", "Vargas", "Vasconcellos", "Viana",
    "Vilela", "Viotti", "Wanderley", "Xavier", "Ximenes", "Zanini", "Zara", "Zeferino",
    "Zerbini", "Abbate", "Accioli", "Accorsi", "Agostini", "Agostinho", "Albanesi", "Alberti",
    "Alessi", "Amato", "Ambrosi", "Andreasi", "Andreis", "Andreoni", "Angeli", "Anghetti",
    "Angiolini", "Antoniazzi", "Antoniolli", "Antonioli", "Armani", "Arnaldi", "Arrighi", "Artoni",
    "Ascenção", "Astori", "Avanzini", "Bacci", "Baglietto", "Baldini", "Barbieri", "Bardini",
    "Barreto", "Bartolini", "Bartoloni", "Bartolucci", "Bassetti", "Battaglini", "Battistini", "Belotti",
    "Benedetti", "Benetton", "Benini", "Benvenuti", "Bertolasi", "Bertolazi", "Bertoldi", "Bertolini",
    "Bertolucci", "Bertoni", "Bertozzi", "Bianchi", "Bianchini", "Bianconi", "Bignami", "Bizzarro",
    "Bocchi", "Boin", "Bonanomi", "Bonato", "Bonetti", "Boni", "Bordonaro", "Borsari",
    "Boschi", "Bosio", "Bottaro", "Brambilla", "Bravi", "Brunelli", "Brunetti", "Bruno",
    "Bucci", "Bui", "Burini", "Burri", "Buscemi", "Bussotti", "Bussolini", "Cafagna",
    "Cagnotti", "Calamari", "Callegari", "Calori", "Calvani", "Calvi", "Campi", "Campigotto",
    "Candido", "Canellas", "Capelli", "Capraro", "Carboni", "Carli", "Carlini", "Carnevali",
    "Carosi", "Carpinetti", "Carta", "Casagrande", "Casanova", "Casiraghi", "Castellani", "Castelli",
    "Cattaneo", "Cavalheiro", "Cavalli", "Cavallini", "Cecchetti", "Cella", "Cervantes", "Cesare",
    "Chiappetta", "Chiavegato", "Chierichetti", "Chierotti", "Ciaramicoli", "Cilento", "Cilloni", "Cinelli",
    "Cipolla", "Cipollone", "Cirelli", "Bauer", "Becker", "Berger", "Bergmann", "Bohm",
    "Brandt", "Brun", "Brunner", "Busch", "Danner", "Decker", "Diesel", "Diehl",
    "Drees", "Dreher", "Drissen", "Ebert", "Ebling", "Echer", "Ecker", "Eckhoff",
    "Ehlers", "Ehmke", "Ehrlich", "Eichler", "Eisenhardt", "Emmel", "Engel", "Engelhardt",
    "Engler", "Erdmann", "Feiler", "Feldmann", "Ferber", "Fiedler", "Fischer", "Fischmann",
    "Fleck", "Flor", "Frank", "Franke", "Franzen", "Freyer", "Friedrich", "Fuchs",
    "Gasser", "Gieseler", "Glaser", "Glock", "Graf", "Grahl", "Grass", "Greff",
    "Greiner", "Gressler", "Grimm", "Gripp", "Grüber", "Gruber", "Grund", "Günter",
    "Haas", "Hack", "Hamann", "Hammes", "Hanauer", "Hansen", "Hartmann", "Hauck",
    "Hausmann", "Heck", "Heckmann", "Heil", "Heimann", "Heinrich", "Heise", "Held",
    "Heller", "Helm", "Hermann", "Hesse", "Hilbert", "Hofer", "Hofmann", "Holzschuh",
    "Hopf", "Horn", "Hornburg", "Huber", "Jäger", "Jahn", "Jakob", "Jost",
    "Jung", "Kaiser", "Kaminski", "Kannenberg", "Kiefer", "Kirst", "Klein", "Klement",
    "Klinger", "Koch", "Koerich", "Kohlmann", "Kopf", "Kossmann", "Kramer", "Krause",
    "Krebs", "Kremer", "Kroener", "Krueger", "Kruse", "Kühn", "Kunz", "Kurz",
    "Lang", "Lange", "Langer", "Lehmann", "Lemke", "Lenz", "Liebich", "Linke",
    "Lisowski", "Löffler", "Lorenz", "Luca", "Luck", "Ludwig", "Lüdtke", "Lutterbeck",
    "Mäder", "Maier", "Manske", "Marchetti", "Maske", "Mayer", "Meier", "Meissner",
    "Meller", "Mende", "Mentz", "Mergen", "Merten", "Metz", "Metzger", "Meyer",
    "Michel", "Michels", "Tanaka", "Suzuki", "Watanabe", "Yamamoto", "Nakamura", "Kobayashi",
    "Ito", "Kato", "Saito", "Yamada", "Hayashi", "Kimura", "Matsumoto", "Inoue",
    "Kinoshita", "Ogawa", "Hashimoto", "Nishimura", "Abe", "Fujita", "Okamoto", "Nakajima",
    "Hasegawa", "Yamaguchi", "Shimizu", "Ikeda", "Matsuda", "Fujii", "Sasaki", "Hayakawa",
    "Mori", "Ota", "Kubota", "Tsuda", "Ishii", "Noguchi", "Goto", "Hirano",
    "Sakamoto", "Takahashi", "Ueda", "Kaneko", "Kawamoto", "Konno", "Kuroda", "Makino",
    "Marusho", "Masuda", "Matsuo", "Abade", "Abilio", "Aboim", "Abraão", "Abrunhosa",
    "Acioli", "Acosta", "Adão", "Adorno", "Afonso", "Agueda", "Aguilar", "Alarcão",
    "Albergaria", "Albino", "Alcantara", "Alcobia", "Alcochel", "Aldeia", "Aldrovandi", "Alegria",
    "Alencastro", "Alfonsin", "Alheiro", "Alifonso", "Almada", "Almeidal", "Altino", "Alvarengas",
    "Alvelos", "Alvinhos", "Alvisio", "Alzira", "Amancio", "Amanta", "Amaro", "Amavizca",
    "Amazónia", "Ambiel", "Ambrogio", "Ambroses", "Ambrosio", "Ameal", "Ameixa", "Ameixial",
    "Ameixoeira", "Amelinha", "Amende", "Ameral", "Amércio", "Americo", "Amerino", "Amernes",
    "Amero", "Amerus", "Amesquita", "Amestoy", "Amevo", "Amezola", "Amil", "Amilaga",
    "Amilde", "Amiles", "Amilhoa", "Amilis", "Amilo", "Amira", "Amiraldo", "Amiran",
    "Amirate", "Amirau", "Amiral", "Amirala", "Andriolo", "Anibal", "Anísio", "Anjinho",
    "Annecy", "Annunziata", "Antelo", "Antelmo", "Antenor", "Antero", "Antigao", "Antipa",
    "Antipas", "Antipode", "Antolini", "Antonas", "Antonelli", "Antunes", "Anunciação", "Anunciato",
    "Anzolin", "Aoki", "Aparicio", "Aparo", "Apolonia", "Appolonio", "Apuzzo", "Aquino",
    "Aquires", "Araçatuba", "Aracy", "Arafat", "Arago", "Aragones", "Aragoni", "Aragão",
    "Aralho", "Aramburu", "Aramis", "Aranda", "Arantes", "Aranzales", "Arão", "Araujo",
    "Araxá", "Arcadio", "Arcanjo", "Archane", "Archanjo", "Archanno", "Archave", "Archela",
    "Archello", "Archer", "Archetti", "Archimedes", "Arcidiacono", "Arcie", "Arcieri", "Arcila",
    "Arcillas", "Arcin", "Arcini", "Arciniega", "Arcino", "Arcioni", "Arcipreste", "Arcis",
    "Arcola", "Arcon", "Arconde", "Arconet", "Arconi", "Arconte", "Arconti", "Arcos",
    "Arcosi", "Arcot", "Arcoverde", "Ardaillon", "Ardani", "Ardao", "Ardeal", "Arden",
    "Ardena", "Ardene", "Ardeni", "Ardenna", "Ardent", "Arder", "Ardila", "Ardiles",
    "Ardin", "Ardina", "Ardissone", "Ardito", "Ardon", "Ardone", "Ardovino", "Arduchat",
    "Arduchin", "Arduin", "Arduno",
]

# ── Extensão para ampliar diversidade regional (Artigo 4) ─────────────────
# Nomes contemporâneos, nordestinos e indígenas/afro-brasileiros pouco
# representados na lista original — reduz colisões de nome completo e
# aproxima o dataset da diversidade real de uma empresa brasileira.
NOMES_MASCULINOS_EXT = [
    "Ryan", "Emanuel", "Miguel", "Vicente", "Benjamin", "Cauê", "Yuri", "Vitor",
    "Josué", "Douglas", "Everaldo", "Genivaldo", "Robervaldo", "Aldemir", "Anacleto",
    "Cassio", "Deusdedit", "Erivan", "Genildo", "Iarley", "Jamerson", "Josenildo",
    "Marconi", "Nivaldo", "Robevaldo", "Valter", "Wanderson", "Ubirajara", "Iberê",
    "Potiguar", "Araci", "Jandaia", "Yaguarê", "Tupã", "Piraí",
]
NOMES_FEMININOS_EXT = [
    "Isis", "Manuela", "Liz", "Cecília", "Antonella", "Melissa", "Yolanda", "Marisa",
    "Elisangela", "Genilda", "Ivanice", "Jaciete", "Josenilde", "Marconita", "Rosivalda",
    "Valdenice", "Wanderleia", "Iracelma", "Jandaia", "Potira", "Iara", "Moema",
    "Jaci", "Ubirajara" + "ma",  # variação fictícia de nome indígena feminino
    "Araci", "Cauana", "Jandira",
]
SOBRENOMES_EXT = [
    "Nakashima", "Uehara", "Miyazaki", "Takeda", "Furukawa", "Yoshida",
    "Petraglia", "Falchi", "Bevilacqua", "Cassaro", "Grimaldi",
    "Weiss", "Zimmer", "Vogt", "Riedel", "Schaefer",
    "Nascimento", "Trindade", "Bomfim", "Aragão", "Feitosa", "Uchôa",
    "Beserra", "Chagas", "Espírito Santo", "Menezes", "Portela",
]

NOMES_MASCULINOS = NOMES_MASCULINOS + NOMES_MASCULINOS_EXT
NOMES_FEMININOS = NOMES_FEMININOS + NOMES_FEMININOS_EXT
SOBRENOMES = SOBRENOMES + SOBRENOMES_EXT
